branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - { type: "feat", release: "minor" }
        - { type: "fix", release: "patch" }
        - { type: "perf", release: "patch" }
        - { type: "docs", release: "patch" }
        - { type: "chore", release: "patch" }
        - { type: "build", release: "patch" }
        - { type: "refactor", release: "patch" }
        - { type: "test", release: "patch" }
        - { type: "ci", release: "patch" }
        - { type: "style", release: "patch" }
        - { type: "revert", release: "patch" }
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: |
        /usr/bin/env bash -c '
          VERSION="${nextRelease.version}"
          # Update pyproject.toml version
          sed -i "" "s/^version = \".*\"/version = \"${VERSION}\"/" pyproject.toml
          echo "✓ pyproject.toml → v${VERSION}"
        '
  - "@semantic-release/changelog"
  - - "@semantic-release/git"
    - assets:
        - pyproject.toml
        - CHANGELOG.md
      message: "chore(release): ${nextRelease.version} [skip ci]\n\nSRED-Type: support-work\nSRED-Claim: ATR-ADAPTIVE-LAGUERRE"
  - - "@semantic-release/exec"
    - successCmd: "/usr/bin/env bash -c 'git push --follow-tags origin main && echo ✓ Pushed to origin'"
  - "@semantic-release/github"
