branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - { type: "feat", release: "minor" }
        - { type: "fix", release: "patch" }
        - { type: "perf", release: "patch" }
        - { type: "docs", release: "patch" }
        - { type: "chore", release: "patch" }
        - { type: "build", release: "patch" }
        - { type: "refactor", release: "patch" }
        - { type: "test", release: "patch" }
        - { type: "ci", release: "patch" }
        - { type: "style", release: "patch" }
        - { type: "revert", release: "patch" }
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: "sed -i '' 's/^version = \".*\"/version = \"${nextRelease.version}\"/' pyproject.toml && echo '✓ pyproject.toml → v${nextRelease.version}'"
  - "@semantic-release/changelog"
  - - "@semantic-release/git"
    - assets:
        - pyproject.toml
        - CHANGELOG.md
      message: "chore(release): ${nextRelease.version}\n\nSRED-Type: support-work\nSRED-Claim: ATR-ADAPTIVE-LAGUERRE"
  - "@semantic-release/github"
