"""
Regression test for memory efficiency refactoring.

Guarantees bit-for-bit equivalence of all feature values before/after
refactoring by comparing against golden snapshot files generated
before any code changes.

Golden snapshots generated by: tests/test_features/generate_golden_snapshots.py
"""

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from atr_adaptive_laguerre import ATRAdaptiveLaguerreRSI, ATRAdaptiveLaguerreRSIConfig

FIXTURES_DIR = Path(__file__).resolve().parents[1] / "fixtures"


def _generate_ohlcv(n_bars: int = 600) -> pd.DataFrame:
    """Reproduce exact OHLCV data matching golden snapshot generation."""
    np.random.seed(42)
    base_price = 100 + np.cumsum(np.random.randn(n_bars) * 0.5)
    close = base_price
    open_ = close + np.random.randn(n_bars) * 0.3
    high = np.maximum(close, open_) + np.abs(np.random.randn(n_bars) * 0.2)
    low = np.minimum(close, open_) - np.abs(np.random.randn(n_bars) * 0.2)
    volume = np.random.randint(1000, 10000, n_bars)
    dates = pd.date_range("2024-01-01", periods=n_bars, freq="5min")
    return pd.DataFrame(
        {"date": dates, "open": open_, "high": high, "low": low, "close": close, "volume": volume}
    )


def _compare_golden(features: pd.DataFrame, golden_values: np.ndarray, golden_columns: np.ndarray) -> None:
    """Compare features against golden snapshot with NaN-aware exact matching."""
    assert list(features.columns) == list(golden_columns), (
        f"Column mismatch: {sorted(set(features.columns) ^ set(golden_columns))}"
    )
    for i, col in enumerate(golden_columns):
        actual = features[col].values
        expected = golden_values[:, i]
        # NaN-aware comparison: both NaN = match, one NaN = mismatch
        both_nan = np.isnan(actual) & np.isnan(expected)
        either_nan = np.isnan(actual) | np.isnan(expected)
        nan_mismatch = either_nan & ~both_nan
        value_mismatch = ~either_nan & (actual != expected)
        diff_mask = nan_mismatch | value_mismatch
        if diff_mask.any():
            idx = int(np.argmax(diff_mask))
            pytest.fail(
                f"Feature '{col}' diverged at index {idx}: "
                f"expected {expected[idx]!r}, got {actual[idx]!r}"
            )


class TestGoldenSnapshotRegression:
    """Bit-for-bit regression against golden snapshots."""

    @pytest.fixture
    def ohlcv(self) -> pd.DataFrame:
        return _generate_ohlcv()

    def test_single_interval_43_features_exact(self, ohlcv: pd.DataFrame) -> None:
        """Verify all 43 single-interval features match golden snapshot exactly."""
        golden_values = np.load(FIXTURES_DIR / "golden_single_43.npy")
        golden_columns = np.load(FIXTURES_DIR / "golden_columns_43.npy", allow_pickle=True)

        config = ATRAdaptiveLaguerreRSIConfig.single_interval()
        indicator = ATRAdaptiveLaguerreRSI(config)
        features = indicator.fit_transform_features(ohlcv)

        _compare_golden(features, golden_values, golden_columns)

    def test_multi_interval_169_features_exact(self, ohlcv: pd.DataFrame) -> None:
        """Verify all 169 multi-interval unfiltered features match golden snapshot exactly."""
        golden_values = np.load(FIXTURES_DIR / "golden_multi_169.npy")
        golden_columns = np.load(FIXTURES_DIR / "golden_columns_169.npy", allow_pickle=True)

        config = ATRAdaptiveLaguerreRSIConfig.multi_interval(
            multiplier_1=3, multiplier_2=12, filter_redundancy=False
        )
        indicator = ATRAdaptiveLaguerreRSI(config)
        features = indicator.fit_transform_features(ohlcv)

        _compare_golden(features, golden_values, golden_columns)

    def test_multi_interval_121_features_exact(self, ohlcv: pd.DataFrame) -> None:
        """Verify all 121 filtered features match golden snapshot exactly."""
        golden_values = np.load(FIXTURES_DIR / "golden_multi_121.npy")
        golden_columns = np.load(FIXTURES_DIR / "golden_columns_121.npy", allow_pickle=True)

        config = ATRAdaptiveLaguerreRSIConfig.multi_interval(
            multiplier_1=3, multiplier_2=12, filter_redundancy=True
        )
        indicator = ATRAdaptiveLaguerreRSI(config)
        features = indicator.fit_transform_features(ohlcv)

        _compare_golden(features, golden_values, golden_columns)


class TestEdgeCaseRegression:
    """Edge case regression tests (no golden snapshots needed)."""

    def test_flat_prices_no_crash(self) -> None:
        """Flat prices (zero ATR) must not cause division-by-zero crash."""
        n_bars = 100
        dates = pd.date_range("2024-01-01", periods=n_bars, freq="5min")
        ohlcv = pd.DataFrame(
            {"date": dates, "open": 100.0, "high": 100.0, "low": 100.0, "close": 100.0, "volume": 1000}
        )
        config = ATRAdaptiveLaguerreRSIConfig.single_interval()
        indicator = ATRAdaptiveLaguerreRSI(config)
        features = indicator.fit_transform_features(ohlcv)
        assert features.shape == (n_bars, 43)
        assert not features.isna().any().any()

    def test_monotonic_increasing_prices(self) -> None:
        """Monotonically increasing prices must produce valid features."""
        n_bars = 100
        dates = pd.date_range("2024-01-01", periods=n_bars, freq="5min")
        prices = 100.0 + np.arange(n_bars) * 0.5
        ohlcv = pd.DataFrame(
            {"date": dates, "open": prices - 0.1, "high": prices + 0.1, "low": prices - 0.2, "close": prices, "volume": 1000}
        )
        config = ATRAdaptiveLaguerreRSIConfig.single_interval()
        indicator = ATRAdaptiveLaguerreRSI(config)
        features = indicator.fit_transform_features(ohlcv)
        assert features.shape == (n_bars, 43)
        assert not features.isna().any().any()
